export const env = {

    NEXT_PUBLIC_FIREBASE_API_KEY:"AIzaSyBS9QGlpihzZ-zLz1I6xZngQQLdRkzHs7g",
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:"kuvashose.firebaseapp.com",
    NEXT_PUBLIC_FIREBASE_DATABASE_URL:"https://kuvashose.firebaseio.com",
    NEXT_PUBLIC_FIREBASE_PROJECT_ID:"kuvashose",
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:"kuvashose.appspot.com",
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:"891118479292",
    NEXT_PUBLIC_FIREBASE_APP_ID:"1:891118479292:web:f901e3975d67b33d7b6db9",
    NEXT_PUBLIC_FIREBASE_MESERMENT:"G-VTHPPL8LYL",
    PUBLIC_VAPID_KEY:'BJc_FqFXOGR_dfvDXglS98-Ya9X5ZBzhaUH7GD7tdXTZdGVNsPxcwdulNFW_TjMju4l3hCRSy4an_vUOkSQTsnc'
  }